version: "2.1"

services:

  php:
    image: "zeroboh/php:7.1-fpm-alpine"
    links:
      - "mariadb"
      - "redis"
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"  
    volumes:
      - "./:/data/"

  nginx:
    image: "zeroboh/nginx:1.11-alpine"
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    links:
      - "php"
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"
      NGINX_PORT: "${NGINX_PORT}"
    command: /bin/sh -c "/data/Docker/run_nginx.sh"
    volumes:
      - "./:/data/"

  redis:
     image: "zeroboh/redis:3.2-alpine"

  mariadb:
    image: "zeroboh/mariadb:10.1-debian-jessie"
    volumes:
      - ./Docker/mariadb:/var/lib/mysql
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
