version: "2"

services:

  php:
    build: ./Docker/php-fpm
    links:
      - "mariadb"
      - "redis"
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"
    volumes:
      - "./Data:/data"

  nginx:
    build: ./Docker/nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    links:
      - "php"
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"
      NGINX_PORT: "${NGINX_PORT}"
      NGINX_DOCUMENT_ROOT: "${NGINX_DOCUMENT_ROOT}"
    command: /bin/sh -c "/run_nginx.sh"
    volumes_from:
      - php

  redis:
     build: ./Docker/redis

  mariadb:
    build: ./Docker/mariadb
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - "./MariaDB:/var/lib/mysql"
