version: "2.1"

services:

  php:
    image: ${IMAGE_PHP}
    links:
      - "mariadb"
      - "redis"
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"  
    volumes:
      - "./:/data/"

  nginx:
    image: ${IMAGE_NGINX}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    links:
      - "php"
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"
      NGINX_PORT: "${NGINX_PORT}"
    command: /bin/sh -c "/data/Docker/run_nginx.sh"
    volumes:
      - "./:/data/"

  redis:
     image: ${IMAGE_REDIS}

  mariadb:
    image: ${IMAGE_MARIADB}
    volumes:
      - "./Docker/mariadb:/var/lib/mysql"
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
