version: "2"

services:

  php:
    image: "zeroboh/php:7.1-fpm-alpine"
    links:
      - "mariadb"
      - "redis"
    volumes:
      - "./:/data/"

  nginx:
    image: "zeroboh/nginx:1.11-alpine"
    ports:
      - "32831:32831"
    links:
      - "php"
    volumes:
      - "./:/data/"
      - "./Docker/default.conf:/etc/nginx/conf.d/default.conf"

  redis:
     image: "zeroboh/redis:3.2-alpine"

  mariadb:
    image: "zeroboh/mariadb:10.1-debian-jessie"
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "neos"
      MYSQL_DATABASE: "neos"
      MYSQL_USER: "neos"
      MYSQL_PASSWORD: "neos"
