version: "2"

services:

  php:
    build: ./Docker/php-fpm
    image: ${PROJECT_IDENTIFIER}/php-fpm:7.1-fpm-alpine
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"
    depends_on:
      - "redis"
      - "mariadb"  
    volumes:
      - "./Data:/data"

  nginx:
    build: ./Docker/nginx
    image: ${PROJECT_IDENTIFIER}/nginx:1.11-alpine
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"
      NGINX_PORT: "${NGINX_PORT}"
      NGINX_DOCUMENT_ROOT: "${NGINX_DOCUMENT_ROOT}"
    depends_on:
      - "php"
    volumes_from:
      - "php"

  redis:
     build: ./Docker/redis
     image: ${PROJECT_IDENTIFIER}/redis:3.2-alpine

  mariadb:
    build: ./Docker/mariadb
    image: ${PROJECT_IDENTIFIER}/mariadb:10.1-debian-jessie
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - "./MariaDB:/var/lib/mysql"
